### PR TITLE
My kids set class is done

### PR DESCRIPTION
**Pull request by SedaYurdakul**
Finished MyKidsSet class

### CODE REVIEW

**Review by yahyaayabakan — COMMENTED** [review]
good start

**Review by yahyaayabakan — COMMENTED** [review]
right variables and constructors

**Review by yahyaayabakan — COMMENTED** [review]
perfect methods

**Review by yahyaayabakan — COMMENTED** [review]
no problem at all
ready to merge
congratulations

**Comment by lauraistoc** [comment]
Good class.

**Review by tsulun — APPROVED** [review]
seems ready to merge, perfect job

**Pull request merged**
