### PR TITLE
Finished my Comparable kids set Classes

### PR DESCRIPTION
**Pull request by lauraistoc**
Both classes are done.

### CODE REVIEW

**Review by yahyaayabakan — COMMENTED** [review]
good start

**Review by yahyaayabakan — COMMENTED** [review]
right variables

**Review by yahyaayabakan — COMMENTED** [review]
perfect switch statement

**Review by yahyaayabakan — COMMENTED** [review]
good to go

**Review by yahyaayabakan — COMMENTED** [review]
congratulations

**Review by yahyaayabakan — COMMENTED** [review]
well done

**Review by SedaYurdakul — APPROVED** [review]
very good!

**Pull request closed without merging**
