### PR TITLE
mySofa Class

### PR DESCRIPTION
**Pull request by tsulun**
class is done and ready to merge

### CODE REVIEW

**Review by lauraistoc — COMMENTED** [review]
Everything is good.

**Review by yahyaayabakan — COMMENTED** [review]
nice kick start

**Review by yahyaayabakan — COMMENTED** [review]
good imports
lol

**Review by yahyaayabakan — COMMENTED** [review]
right variables

**Review by yahyaayabakan — COMMENTED** [review]
state of the art methods

**Review by SedaYurdakul — APPROVED** [review]
Perfect and ready to go..

**Pull request merged**
